### ISSUE TITLE
video not saved in /video folder showing some error

### ISSUE THREAD

**Issue by zeeshanmahar007** [dxli94/WLASL#32]
when I run Preprocess script then only .mp4 video saved in raw_videos_mp4 folder and discard .swf file and after that show this error and only 3 video saved in videos folder.

Finish converting formats..
2 videos\69241.mp4
Traceback (most recent call last):
  File "preprocess.py", line 128, in <module>
    main()
  File "preprocess.py", line 124, in main
    extract_all_yt_instances(content)
  File "preprocess.py", line 93, in extract_all_yt_instances
    selected_frames = extract_frame_as_video(src_video_path, start_frame, end_frame)
  File "preprocess.py", line 52, in extract_frame_as_video
    frames = video_to_frames(src_video_path)
  File "preprocess.py", line 28, in video_to_frames
    ret, frame = cap.read()
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-cff9bdsm\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 676080 bytes in function 'cv::OutOfMemoryError'

**Comment by waduhekx** [comment]
I trid to use check all "swf" files, all of them are same. Because when we tried  to download video from "www.aslpro.com" , we got the error "url" page,   not a video.

And I trid to use cv2 get frames from video, it's not works too.
