### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by atheeraa** [dxli94/WLASL#33]
Hello, 
I'm getting this error: 
{'word': '/content/drive/MyDrive/WLASL/code/I3D/data/videos'} preprocess/nslt_100.json
bs=6_ups=1_lr=0.0001_eps=0.001_wd=1e-08
Skipped videos:  0
275
Skipped videos:  0
92
Step 0/64000
----------
12313
/content/drive/MyDrive/WLASL/code/I3D/data/videos/12313.mp4
70107
/content/drive/MyDrive/WLASL/code/I3D/data/videos/70107.mp4
23779
/content/drive/MyDrive/WLASL/code/I3D/data/videos/23779.mp4
70245
/content/drive/MyDrive/WLASL/code/I3D/data/videos/70245.mp4
06368
/content/drive/MyDrive/WLASL/code/I3D/data/videos/06368.mp4
05750
/content/drive/MyDrive/WLASL/code/I3D/data/videos/05750.mp4
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3509: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3635: UserWarning: Default upsampling behavior when mode=linear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
00618
/content/drive/MyDrive/WLASL/code/I3D/data/videos/00618.mp4
40843
/content/drive/MyDrive/WLASL/code/I3D/data/videos/40843.mp4
42974
/content/drive/MyDrive/WLASL/code/I3D/data/videos/42974.mp4
30841
/content/drive/MyDrive/WLASL/code/I3D/data/videos/30841.mp4
07069
/content/drive/MyDrive/WLASL/code/I3D/data/videos/07069.mp4
65445
/content/drive/MyDrive/WLASL/code/I3D/data/videos/65445.mp4
70211
/content/drive/MyDrive/WLASL/code/I3D/data/videos/70211.mp4
42838
/content/drive/MyDrive/WLASL/code/I3D/data/videos/42838.mp4
12319
/content/drive/MyDrive/WLASL/code/I3D/data/videos/12319.mp4
17722
/content/drive/MyDrive/WLASL/code/I3D/data/videos/17722.mp4
Traceback (most recent call last):
  File "train_i3d.py", line 205, in <module>
    run(configs=configs, mode=mode, root=root, save_model=save_model, train_split=train_split, weights=weights)
  File "train_i3d.py", line 116, in run
    for data in dataloaders[phase]:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/WLASL/code/I3D/datasets/nslt_dataset.py", line 182, in __getitem__
    imgs = load_rgb_frames_from_video(self.root['word'], vid, start_f, total_frames)
  File "/content/drive/My Drive/WLASL/code/I3D/datasets/nslt_dataset.py", line 57, in load_rgb_frames_from_video
    w, h, c = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'

I printed the paths of the videos to make sure I'm in the right directory, can you tell me what's the problem here?

**Comment by atheeraa** [comment]
For anyone facing the same issue, it turns out this error is caused by the missing videos, either contact the developers to get the missing videos, or modify the code - load_rgb_from_video funciton - so that it would check if a video is missing, if so, ignore it and move to next video
